sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-101.pdf --upload --lsstdoc DMTN-101.tex --env=travis --ltd-product dmtn-101"
env:
  global:
    # Add LSST the Docs credentials
    - secure: "X1Qm2yWWwXq1hMQWeoACJ/Bamc3Ze5yQMLxXqRfk55M7muGgi5FkORTjF//S5wZDkr4SFJh8iHRs0gneKte9UY/QfWErRovzUXb9CRLdRWUQvZ4H0w9WqQfwLlY43jDKXbkFUuYhcBYos7NTHFxvDVBRLknmndIXS4RLUHwTUr/LSE8DkuURQwFRZnyzl4n+WtdjUNVPE3tzmge92DF3NHpa4u9VKGXd1U/q/IdN/FifPkOjlGjNAaYtvYP4fl68WHrAltWEQEMqZBkAdiwwLYoBHtu0fIka8+ZInCyOBNQsx0aTCybWWZhJTTzJqC3LCe1icX1q9OSaGpiY1ONAYfn/vk5W2VdXQj5+Fs0jA8kXCAjWi9x+iFLDl32otLKl+mRl3828YbPhBPOcOlHDH7/x/8Iyo0iq0thRirVO7EWWD/c0WVXvCv8pp2WGXvWWM+Bnn012pQq7SErb8Hnp1veXYEA3EeV7mgZLjUR7TFcHW732gEFAoTeC1kH/M5c+6o0kojBPOMf52JnVEKRKuEIUN8BDdMeibSw7bTshken/Umby/47rrBdoDlsiaDmccyICTRF43eqNuXgoYc29LEIOSK8tfS3f+vFv42rNgAt+gUcV1apb0k6sfAHCD57zWXQ6SUap433itfGDfiOEVD6KMKZdZLJLBOGz8URZhok="
    - secure: "lodldNT1lSbdh9fQSfUiPL/rToHjrBBAL1j8jra1oYJ6XZntE3vdMx84yc3SMpP5i85RNgLmnawsSbPtfhtnrvZYHFHrCiXrNvx2q7l19wsewv5jfrbr5TInIJca+tJstMYoye5ybtFS6n7+MmZmmpeEdDOHdzE+zAFDTalzpXMcQM5zCBlalvFDNM7oLYeoN53erhmiNdBzMNCwyUtSZRD+w2Lt0Cqgv63DmVRYHVNuP3ih9721ZlrS0UWhp7wuu2nRqBYxNluQtprMvEXbcSfbpfLwXVNtk3AyXnW4ez/VDsDojDpQY6dpuqfB9OTfrLbTo15mk0P/n68X6fwKTEcc3qB5LE1Kve9c+SJhHPyMWVxRk2ach+s1t84gXy88AUb1D9b2FYnV60ndvO/1hRxJl7w1z9XzwRwBIlon1+QIg2DLsJuWFvcKf8pUPBYvRHz5H24iyK74h++nbAyK3e5esEpHPDuyrD8RYMdlosgv01PXBPT8buEhfc3iBTxjHnFQcNxEHaz1O1UINOZQM/z9LxjuSyDjwdcZPjkvOoI6PfssvUpmkHLKmPNE4bwwu3f4FIsyAK8EfRxLY5/DIG/ihcshaSciND6ntNvEABw9+w0FEc0UlNIYOGg+FSIPAeRtJbzwMeDnE46g9MgLktjDB6e3m+5MN2OOpfT0fRo="
